// "use client";

import TranslationsProvider from "@/components/TranslationsProvider";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import initTranslations from "../i18n";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const i18nNamespaces = ["home"];

export default async function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: any };
}>) {
    const { t, resources } = await initTranslations(locale, i18nNamespaces);
    return (
        <html lang="en">
            <TranslationsProvider
                namespaces={i18nNamespaces}
                locale={locale}
                resources={resources}
            >
                <body className={inter.className}>{children}</body>
            </TranslationsProvider>
        </html>
    );
}
